theme: jekyll-theme-midnight
title: "Muhammad Tabaza"
description: "Co-founder and CTO of Pragma, Functional Programmer, and Machine Learning enthusiast."
show_downloads: false
google_analytics: "UA-156981056-1"
